services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:0.6.22 # also try :latest
    ports:
      - "3000:8080"
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    environment:
      OFFLINE_MODE: "True"
      ENABLE_RAG_WEB_SEARCH: "True"
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: "3"
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: "10"
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
    restart: always

  ollama:
    container_name: ollama
    image: ollama/ollama:0.11.4 # also try :latest
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
      - /opt/rocm:/opt/rocm:ro  # optional: enables AMD GPUs inference
    devices:
      - /dev/kfd  # optional: enables AMD GPUs inference
      - /dev/dri  # optional: enables AMD GPUs inference
    environment:
      HSA_OVERRIDE_GFX_VERSION: "9.0.c" # optional: enables AMD GPUs inference

  searxng:
    container_name: searxng
    image: searxng/searxng:2025.8.12-6b1516d  # also try :latest
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    env_file:
      - .env
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  ollama:
  open-webui:
