services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "3000:8080"
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    environment:
      ENABLE_RAG_WEB_SEARCH: "True"
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: "3"
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: "10"
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
    restart: always

  ollama:
    container_name: ollama
    image: ollama/ollama:latest

    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - /opt/rocm:/opt/rocm:ro
    restart: unless-stopped
    devices:
      - /dev/kfd
      - /dev/dri
      #- /dev/amdgpu
    group_add:
      - video
    environment:
      HSA_OVERRIDE_GFX_VERSION: "9.0.0"

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    env_file:
      - .env
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  ollama:
  open-webui:
